config/routes.rb
Movieso::Application.routes.draw do
  # 非 API 的域名
  constraints(MainDomainMatcher) do
    match 'captcha' => EasyCaptcha::Controller, :action => :captcha, :via => :get

    devise_for :users, :path => "account", :controllers => {
        :registrations => :account,
        :sessions => :sessions
      } do
    end
    resources :movies do
      collection do
        get :top
        get :series
        get :feed
        get :feed_all
        get :search
        get :weekly
      end
      member do
        get :douban_page
        get :douban_review
        get :fetch_douban
        get :fetch_cover
        get :fetch_bg
        get :fetch_fenopy
        get :fetch_sources
        post :suggest
      end
      resources :attachs
      resources :sources
    end

    resources :attach_entries, :path => 'entries' do
      collection do
        get :search
      end
    end

    resources :users

    root :to => "home#index"
    match "/info1", :to => "home#info1"

    namespace :admin do
      root :to => 'home#index'
      resources :site_configs
      resources :movies do
        member do
          post :delete_attachs
        end
      end
      resources :users
      resources :attach_entries
      namespace :homeland, :path => "bbs" do
        resources :topics
        resources :nodes
        resources :replies
        resources :sections
      end
    end
    mount Homeland::Engine, :at => "/bbs"
  end

  namespace :api do
    resources :movies do
      collection do
        get :search
        post :multi
        get :multi
        get :top
      end
    end
  end
end

app/models/site_config.rb
# coding: utf-8
# 在数据库中的配置信息
# 使用方法
# SiteConfig.foo
# SiteConfig.foo = "asdkglaksdg"
class SiteConfig
  include Mongoid::Document
  include Mongoid::BaseModel

  field :key
  field :value

  index :key

  validates_presence_of :key
  validates_uniqueness_of :key

  def self.method_missing(method, *args)
    method_name = method.to_s
    super(method, *args)
  rescue NoMethodError
    if method_name =~ /=$/
      var_name = method_name.gsub('=', '')
      value = args.first.to_s
      # save
      if item = find_by_key(var_name)
        item.update_attribute(:value, value)
      else
        SiteConfig.create(:key => var_name, :value => value)
      end
    else
      Rails.cache.fetch("site_config:#{method}") do
        if item = find_by_key(method)
          item.value
        else
          nil
        end
      end
    end
  end

  after_save :update_cache
  def update_cache
    Rails.cache.write("site_config:#{self.key}", self.value)
  end

  def self.find_by_key(key)
    where(:key => key.to_s).first
  end

  def self.save_default(key, value)
    create(:key => key, :value => value.to_s) unless find_by_key(key)
  end
end

app/controllers/admin/site_configs_controller.rb
# coding: UTF-8
class Admin::SiteConfigsController < Admin::ApplicationController

  def index
    @site_configs = SiteConfig.recent.paginate(:page => params[:page], :per_page => 20)

    respond_to do |format|
      format.html # index.html.erb
      format.json
    end
  end

  def show
    @site_config = SiteConfig.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json
    end
  end

  def new
    @site_config = SiteConfig.new

    respond_to do |format|
      format.html # new.html.erb
      format.json
    end
  end

  def edit
    @site_config = SiteConfig.find(params[:id])
  end

  def create
    @site_config = SiteConfig.new(params[:site_config])

    respond_to do |format|
      if @site_config.save
        format.html { redirect_to(admin_site_configs_path, :notice => 'Site config 创建成功。') }
        format.json
      else
        format.html { render :action => "new" }
        format.json
      end
    end
  end

  def update
    @site_config = SiteConfig.find(params[:id])

    respond_to do |format|
      if @site_config.update_attributes(params[:site_config])
        format.html { redirect_to(admin_site_configs_path, :notice => 'Site config 更新成功。') }
        format.json
      else
        format.html { render :action => "edit" }
        format.json
      end
    end
  end

  def destroy
    @site_config = SiteConfig.find(params[:id])
    @site_config.destroy

    respond_to do |format|
      format.html { redirect_to(admin_site_configs_path,:notice => "删除成功。") }
      format.json
    end
  end
end

app/views/admin/site_configs/_base.html.erb
<%= content_for :styles do %>
<% end %>

<ul class="nav nav-tabs">
  <li<%= " class=active" if action_name == "index" %>>
    <%= link_to "列表", admin_site_configs_path %>
  </li>
  <% if action_name.in?(%w(edit update)) %>
  <li class="active"><%= link_to "修改", edit_admin_site_config_path(@site_config) %></li>
  <% end %>
  <li<%= " class=active" if action_name.in?(%w(new create)) %>><%= link_to "新建", new_admin_site_config_path %></li>
</ul>

app/views/admin/site_configs/_form.html.erb
<div id="admin_site_config" class="form">

<%= simple_form_for([:admin,@site_config]) do |f| %>
  <%= render "/shared/error_messages", :target => @site_config  %>
  <h2><%= t("site_config.#{@site_config.key}") %></h2>
  <fieldset>
    <%= f.input :key %>
    <%= f.input :value, :as => :text, :input_html => { :class => "span8", :rows => 8 } %>
    <div class="form-actions">
      <%= f.submit "保存", :class => "btn btn-primary" %> or <%= link_to "取消", admin_site_configs_path %>
    </div>
  </fieldset>
<% end %>
</div>

app/views/admin/site_configs/edit.html.erb
<%= render 'base' %>
<%= render 'form' %>

app/views/admin/site_configs/index.html.erb
<%= render 'base' %>
<div id="admin_site_configs">
  <table class="table table-striped table-bordered table-condensed">
    <thead>
      <tr>
        <th>编号</th>
        <th><%= t("mongoid.attributes.site_config.key") %></th>
        <th>说明</th>
        <th class="opts"></th>
      </tr>
    </thead>
    <tbody>
    <% @site_configs.each do |item| %>
    <tr class="<%= cycle("","even") %>">
        <td><%= item.id %></td>
        <td><%= item.key %></td>
        <td><%= t("site_config.#{item.key}") %></td>
        <td>
          <%= link_to "", edit_admin_site_config_path(item.id), :class => "icon-edit" %>
          <%= link_to '', admin_site_config_path(item.id), :method => :delete, :'data-confirm' => '确定要删除吗?', :class => "icon-remove" %>
        </td>
      </tr>
    <% end %>
    <tbody>
  </table>
  <%= will_paginate @site_configs %>
</div>

app/views/admin/site_configs/new.html.erb
<%= render 'base' %>
<%= render 'form' %>

app/views/admin/site_configs/show.html.erb
<%= render 'base' %>
<div id="admin_site_config">
  <%= link_to '修改', edit_admin_site_config_path(@site_config), :class => "btn small success" %>
    <p>
    <b>Key:</b>
    <%= @site_config.key %>
  </p>
    <p>
    <b>Value:</b>
    <%= @site_config.value %>
  </p>
  </div>