config/routes.rb
Movieso::Application.routes.draw do
  # 非 API 的域名
  constraints(MainDomainMatcher) do
    match 'captcha' => EasyCaptcha::Controller, :action => :captcha, :via => :get

    devise_for :users, :path => "account", :controllers => {
        :registrations => :account,
        :sessions => :sessions
      } do
    end
    resources :movies do
      collection do
        get :top
        get :series
        get :feed
        get :feed_all
        get :search
        get :weekly
      end
      member do
        get :douban_page
        get :douban_review
        get :fetch_douban
        get :fetch_cover
        get :fetch_bg
        get :fetch_fenopy
        get :fetch_sources
        post :suggest
      end
      resources :attachs
      resources :sources
    end

    resources :attach_entries, :path => 'entries' do
      collection do
        get :search
      end
    end

    resources :users

    root :to => "home#index"
    match "/info1", :to => "home#info1"

    namespace :admin do
      root :to => 'home#index'
      resources :site_configs
      resources :movies do
        member do
          post :delete_attachs
        end
      end
      resources :users
      resources :attach_entries
      namespace :homeland, :path => "bbs" do
        resources :topics
        resources :nodes
        resources :replies
        resources :sections
      end
    end
    mount Homeland::Engine, :at => "/bbs"
  end

  namespace :api do
    resources :movies do
      collection do
        get :search
        post :multi
        get :multi
        get :top
      end
    end
  end
end

app/views/shared/_admin_navbar.html.erb
<div class="subnav subnav-fixed">
  <div class="container">
  <ul class="nav nav-pills">
    <li<%= " class=active" if params[:controller] == "admin/home" %>><a href="/admin">概况</a></li>
    <li<%= " class=active" if params[:controller] == "admin/site_configs" %>><%= link_to "系统配置", admin_site_configs_path %></li>
    <li<%= " class=active" if params[:controller] == "admin/movies" %>><%= link_to "影片", admin_movies_path %></li>
    <li<%= " class=active" if params[:controller] == "admin/attach_entries" %>><%= link_to "资源", admin_attach_entries_path %></li>
    <li<%= " class=active" if params[:controller] == "admin/users" %>><%= link_to "用户", admin_users_path %></li>
  	<li<%= " class=active" if params[:controller] == "admin/homeland/topics" %>><%= link_to "话题", admin_homeland_topics_path %></li>
  	<li<%= " class=active" if params[:controller] == "admin/homeland/replies" %>><%= link_to "回帖", admin_homeland_replies_path %></li>
  	<li<%= " class=active" if params[:controller] == "admin/homeland/sections" %>><%= link_to "大节点", admin_homeland_sections_path %></li>
  	<li<%= " class=active" if params[:controller] == "admin/homeland/nodes" %>><%= link_to "节点", admin_homeland_nodes_path %></li>
  </ul>
  </div>
</div>

app/views/shared/_breadcrumbs.html.erb
<ul class="breadcrumb">
  <li>
    <a href="<%= main_app.root_path %>" rel="nofollow">首页</a> <% if !@breadcrumbs.blank? %><span class="divider">/</span><% end %>
  </li>
  <% if not @breadcrumbs.blank? %>
    <% @breadcrumbs.each_with_index do |item,i| %>
      <li itemscope itemtype="http://data-vocabulary.org/Breadcrumb">
        <%= link_to raw("<span itemprop='title'>#{item[0]}</span>"), item[1], :rel => "nofollow", :itemprop => "url" %>
        <% if i + 1 < @breadcrumbs.length %>
        <span class="divider">/</span>
        <% end %>
      </li>
    <% end %>
  <% end %>
  <%= yield :breadcrumb %>
  <% if controller_name == "home" and action_name == "index" %>
  <li>
    <%= render "/shared/weibo_share" %>
  </li>
  <% end %>
  <li class="pull-right feed"><%= link_to raw("#{image_tag("feed@2x.png", :style => "width:16px;height:16px;")}订阅资源"), main_app.feed_movies_url %></li>
</ul>

app/views/shared/_captcha_field.html.erb
<div class=="control-group string">
  <%= f.label :captcha %>
  <div class="controls">
    <%= f.input_field :captcha, :style => "width:50px;" %>
    <%= captcha_tag %><a href="#" onclick="return App.reloadCaptcha(this);" rel="twipsy" title="点击可以换一个验证码">看不清</a>
  </div>
</div>

app/views/shared/_comments.html.erb
<div class="ds-thread"></div>
<script type="text/javascript">
var duoshuoQuery = {short_name:"imaxim"};
(function() {
  var ds = document.createElement('script');
  ds.type = 'text/javascript';ds.async = true;
  ds.src = 'http://static.duoshuo.com/embed.js';
  ds.charset = 'UTF-8';
  (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(ds);
})();
</script>

app/views/shared/_error_messages.html.erb
<% if target.errors.any? %>  
 <div class="alert alert-block alert-error">
   <a class="close" href="#">×</a>
   <p><strong>有 <%= target.errors.count %> 处问题导至无法提交:</strong></p>
   <ul>
   <% target.errors.full_messages.each do |msg| %>
     <li><%= msg %></li>
   <% end %>
   </ul>
 </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container">
    <% if mobile? %>
    &copy; IMAX.im <br />
    <%= link_to "电影周刊", main_app.weekly_movies_path, :target => "_blank" %> •
    <%= link_to "论坛", homeland.root_path %> •
    <a href="#">返回顶部</a>
    <% else %>
      <%= yield :footer %>
      <p class="pull-right"><a href="#">回到顶部</a></p>
      <p><%=raw SiteConfig.footer_html %></p>
      <% if !DoubanRequest.allow? %>
      <small>Douban API 请求已经超支。</small>
      <% end %>
    <% end %>
  </div>
</footer>

<div style="width:0px;height:0px;overflow:hidden;">
<script type="text/javascript">
var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");
document.write(unescape("%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%3F68bb726ab7e17fd4cf0869ece9a87a6f' type='text/javascript'%3E%3C/script%3E"));
</script>
</div>

app/views/shared/_nav_search.html.erb
<form class="navbar-search" action="/movies/search">
  <div class="input-append">
    <input type="text" name="q" class="search-query span3" value="<%= params[:q] %>" placeholder="输入关键词，搜索资源">
    <button type="submit" class="btn btn-success"><i class="icon-search icon-white"></i></button>
  </div>
</form>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to image_tag("logo.png", :style => "width:95px;height:35px;"), main_app.root_path, :class => "brand span2" %>
      <ul class="nav main-nav">
        <li<%= " class=active" if params[:controller] == "home" %>><%= link_to "首页", main_app.root_path %></li>
        <li<%= " class=active" if params[:controller] == "movies" && !params[:action].in?(%w(series top)) && @is_series.blank? %>><%= link_to "电影", main_app.movies_path %></li>
        <li<%= " class=active" if (params[:controller] == "movies" && params[:action] == "series") || @is_series == true %>><%= link_to "电视剧", main_app.series_movies_path %></li>
        <li<%= " class=active" if params[:controller] == "movies" && params[:action] == "top" %>><%= link_to "高分", main_app.top_movies_path %></li>
		    <li<%= " class=active" if params[:controller].match("homeland") %> id="nav-bbs"><%= link_to "论坛", homeland.root_path %></li>
        <li class="search_box" style="margin-left:20px;">
          <%= render "/shared/nav_search" %>
        </li>
      </ul>
      <ul class="nav user-bar pull-right">
        <% if current_user %>
          <li><%= link_to current_user.name, main_app.user_path(current_user) %></li>
          <li class="dropdown" id="user_menu">
            <a href="#user_menu" class="dropdown-toggle" data-toggle="dropdown">
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to("个人页面",main_app.user_path(current_user)) %></li>
              <li class="divider"></li>
              <li><%= link_to("修改个人资料",main_app.edit_user_registration_path) %></li>
              <% if admin? %>
              <li<%= " class=active" if controller.send(:_layout) == "admin" %>><%= link_to "后台", main_app.admin_root_path %></li>
              <% end %>
              <li class="divider"></li>
              <li><%= link_to("登出", main_app.destroy_user_session_path, :method => :delete ) %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "注册", main_app.new_user_registration_path(:return => request.path), :rel => "nofollow" %></li>
          <li><%= link_to raw("登录"), main_app.new_user_session_path(:return => request.path), :rel => "nofollow" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>
<% if mobile? %>
  <%= render "/shared/nav_search" %>
<% end %>

app/views/shared/_weibo_share.html.erb
<script type="text/javascript" charset="utf-8">
  (function(){
    var _w = 72 , _h = 16;
    var url = location.href.split("?")[0];
    if (url == "http://imax.im/movies") { url = "http://imax.im"; }
    var param = {
      url: url,
      type:'3',
      count:'1',
      appkey:'4070689306',
      title:'',
      pic:'',
      language:'zh_cn',
      ralateUid : '2799362972',
      rnd:new Date().valueOf()
    }
    var temp = [];
    for( var p in param ){
      temp.push(p + '=' + encodeURIComponent( param[p] || '' ) )
    }
    document.write('<iframe style="margin-bottom:-4px;margin-left:20px;" allowTransparency="true" frameborder="0" scrolling="no" src="http://hits.sinajs.cn/A1/weiboshare.html?' + temp.join('&') + '" width="'+ _w+'" height="'+_h+'"></iframe>')
  })()
</script>