config/routes.rb
Movieso::Application.routes.draw do
  # 非 API 的域名
  constraints(MainDomainMatcher) do
    match 'captcha' => EasyCaptcha::Controller, :action => :captcha, :via => :get

    devise_for :users, :path => "account", :controllers => {
        :registrations => :account,
        :sessions => :sessions
      } do
    end
    resources :movies do
      collection do
        get :top
        get :series
        get :feed
        get :feed_all
        get :search
        get :weekly
      end
      member do
        get :douban_page
        get :douban_review
        get :fetch_douban
        get :fetch_cover
        get :fetch_bg
        get :fetch_fenopy
        get :fetch_sources
        post :suggest
      end
      resources :attachs
      resources :sources
    end

    resources :attach_entries, :path => 'entries' do
      collection do
        get :search
      end
    end

    resources :users

    root :to => "home#index"
    match "/info1", :to => "home#info1"

    namespace :admin do
      root :to => 'home#index'
      resources :site_configs
      resources :movies do
        member do
          post :delete_attachs
        end
      end
      resources :users
      resources :attach_entries
      namespace :homeland, :path => "bbs" do
        resources :topics
        resources :nodes
        resources :replies
        resources :sections
      end
    end
    mount Homeland::Engine, :at => "/bbs"
  end

  namespace :api do
    resources :movies do
      collection do
        get :search
        post :multi
        get :multi
        get :top
      end
    end
  end
end

app/controllers/admin/homeland/nodes_controller.rb
# coding: UTF-8
class Admin::Homeland::NodesController < Admin::ApplicationController

  def index
    @nodes = Homeland::Node.desc(:_id).paginate(:page => params[:page], :per_page => 20)

    respond_to do |format|
      format.html # index.html.erb
      format.json
    end
  end

  def show
    @node = Homeland::Node.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json
    end
  end

  def new
    @node = Homeland::Node.new

    respond_to do |format|
      format.html # new.html.erb
      format.json
    end
  end

  def edit
    @node = Homeland::Node.find(params[:id])
  end

  def create
    @node = Homeland::Node.new(params[:node])

    respond_to do |format|
      if @node.save
        format.html { redirect_to(admin_homeland_nodes_path, :notice => 'Node 创建成功。') }
        format.json
      else
        format.html { render :action => "new" }
        format.json
      end
    end
  end

  def update
    @node = Homeland::Node.find(params[:id])

    respond_to do |format|
      if @node.update_attributes(params[:node])
        format.html { redirect_to(admin_homeland_nodes_path, :notice => 'Node 更新成功。') }
        format.json
      else
        format.html { render :action => "edit" }
        format.json
      end
    end
  end

  def destroy
    @node = Homeland::Node.find(params[:id])
    @node.destroy

    respond_to do |format|
      format.html { redirect_to(admin_homeland_nodes_path,:notice => "删除成功。") }
      format.json
    end
  end
end

app/controllers/admin/homeland/replies_controller.rb
# coding: UTF-8
class Admin::Homeland::RepliesController < Admin::ApplicationController

  def index
    @replies = Homeland::Reply.recent.paginate(:page => params[:page], :per_page => 20)

    respond_to do |format|
      format.html # index.html.erb
      format.json
    end
  end

  def show
    @reply = Homeland::Reply.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json
    end
  end

  def new
    @reply = Homeland::Reply.new

    respond_to do |format|
      format.html # new.html.erb
      format.json
    end
  end

  def edit
    @reply = Homeland::Reply.find(params[:id])
  end

  def create
    @reply = Homeland::Reply.new(params[:reply])

    respond_to do |format|
      if @reply.save
        format.html { redirect_to(admin_homeland_replies_path, :notice => 'Reply 创建成功。') }
        format.json
      else
        format.html { render :action => "new" }
        format.json
      end
    end
  end

  def update
    @reply = Homeland::Reply.find(params[:id])

    respond_to do |format|
      if @reply.update_attributes(params[:reply])
        format.html { redirect_to(admin_homeland_replies_path, :notice => 'Reply 更新成功。') }
        format.json
      else
        format.html { render :action => "edit" }
        format.json
      end
    end
  end

  def destroy
    @reply = Homeland::Reply.find(params[:id])
    @reply.destroy

    respond_to do |format|
      format.html { redirect_to(admin_homeland_replies_path,:notice => "删除成功。") }
      format.json
    end
  end
end

app/controllers/admin/homeland/sections_controller.rb
# coding: UTF-8
class Admin::Homeland::SectionsController < Admin::ApplicationController

  def index
    @sections = Homeland::Section.desc(:_id).paginate(:page => params[:page], :per_page => 20)

    respond_to do |format|
      format.html # index.html.erb
      format.json
    end
  end

  def show
    @section = Homeland::Section.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json
    end
  end

  def new
    @section = Homeland::Section.new

    respond_to do |format|
      format.html # new.html.erb
      format.json
    end
  end

  def edit
    @section = Homeland::Section.find(params[:id])
  end

  def create
    @section = Homeland::Section.new(params[:section])

    respond_to do |format|
      if @section.save
        format.html { redirect_to(admin_homeland_sections_path, :notice => 'Section 创建成功。') }
        format.json
      else
        format.html { render :action => "new" }
        format.json
      end
    end
  end

  def update
    @section = Homeland::Section.find(params[:id])

    respond_to do |format|
      if @section.update_attributes(params[:section])
        format.html { redirect_to(admin_homeland_sections_path, :notice => 'Section 更新成功。') }
        format.json
      else
        format.html { render :action => "edit" }
        format.json
      end
    end
  end

  def destroy
    @section = Homeland::Section.find(params[:id])
    @section.destroy

    respond_to do |format|
      format.html { redirect_to(admin_homeland_sections_path,:notice => "删除成功。") }
      format.json
    end
  end
end

app/controllers/admin/homeland/topics_controller.rb
# coding: UTF-8
class Admin::Homeland::TopicsController < Admin::ApplicationController

  def index
    @topics = Homeland::Topic.recent.paginate(:page => params[:page], :per_page => 20)

    respond_to do |format|
      format.html # index.html.erb
      format.json
    end
  end

  def show
    @topic = Homeland::Topic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json
    end
  end

  def new
    @topic = Homeland::Topic.new

    respond_to do |format|
      format.html # new.html.erb
      format.json
    end
  end

  def edit
    @topic = Homeland::Topic.find(params[:id])
  end

  def create
    @topic = Homeland::Topic.new(params[:topic])

    respond_to do |format|
      if @topic.save
        format.html { redirect_to(admin_homeland_topics_path, :notice => 'Topic 创建成功。') }
        format.json
      else
        format.html { render :action => "new" }
        format.json
      end
    end
  end

  def update
    @topic = Homeland::Topic.find(params[:id])

    respond_to do |format|
      if @topic.update_attributes(params[:topic])
        format.html { redirect_to(admin_homeland_topics_path, :notice => 'Topic 更新成功。') }
        format.json
      else
        format.html { render :action => "edit" }
        format.json
      end
    end
  end

  def destroy
    @topic = Homeland::Topic.find(params[:id])
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to(admin_homeland_topics_path,:notice => "删除成功。") }
      format.json
    end
  end
end

app/views/admin/homeland/sections/_base.html.erb
<%= content_for :styles do %>
<% end %>

<ul class="nav nav-tabs">
  <li<%= " class=active" if action_name == "index" %>>
    <%= link_to "列表", admin_homeland_sections_path %>
  </li>
  <% if action_name.in?(%w(edit update)) %>
  <li class="active"><%= link_to "修改", edit_admin_homeland_section_path(@admin_homeland_section) %></li>
  <% end %>
  <li<%= " class=active" if action_name.in?(%w(new create)) %>><%= link_to "新建", new_admin_homeland_section_path %></li>
</ul>

app/views/admin/homeland/sections/_form.html.erb
<div id="admin_homeland_section" class="form">

	<%= simple_form_for([:admin,:homeland,@section]) do |f| %>
  <%= render "/shared/error_messages", :target => @section  %>
  <fieldset>
      <%= f.input :name %>
      <%= f.input :sort %>
      <div class="form-actions">
      <%= f.submit "保存", :class => "btn btn-primary" %> or <%= link_to "取消", admin_homeland_sections_path %>
    </div>
  </fieldset>
<% end %>
</div>

app/views/admin/homeland/sections/edit.html.erb
<%= render 'base' %>
<%= render 'form' %>

app/views/admin/homeland/sections/index.html.erb
<%= render 'base' %>
<div id="admin_homeland_sections">
  <table class="table table-striped table-bordered table-condensed">
    <thead>
      <tr>
        <th>编号</th>
        <th><%= t("mongoid.attributes.section.name") %></th>
        <th><%= t("mongoid.attributes.section.sort") %></th>
        <th>创建时间</th>
        <th class="opts"></th>
      </tr>
    </thead>
    <tbody>
    <% @sections.each do |item| %>
    <tr class="<%= cycle("","even") %>">
        <td><%= item.id %></td>
        <td><%= item.name %></td>
        <td><%= item.sort %></td>
        <td><%= l(item.created_at, :format => :long) %></td>
        <td>
          <%= link_to "", edit_admin_homeland_section_path(item.id), :class => "icon-edit" %>
          <%= link_to '', admin_homeland_section_path(item.id), :method => :delete, :'data-confirm' => '确定要删除吗?', :class => "icon-remove" %>
        </td>
      </tr>
    <% end %>
    <tbody>
  </table>
  <%= will_paginate @sections %>
</div>

app/views/admin/homeland/sections/new.html.erb
<%= render 'base' %>
<%= render 'form' %>

app/views/admin/homeland/sections/show.html.erb
<%= render 'base' %>
<div id="admin_homeland_section">
  <%= link_to '修改', edit_admin_homeland_section_path(@section), :class => "btn small success" %>
    <p>
    <b>Name:</b>
    <%= @section.name %>
  </p>
    <p>
    <b>Sort:</b>
    <%= @section.sort %>
  </p>
  </div>