config/routes.rb
Movieso::Application.routes.draw do
  # 非 API 的域名
  constraints(MainDomainMatcher) do
    match 'captcha' => EasyCaptcha::Controller, :action => :captcha, :via => :get

    devise_for :users, :path => "account", :controllers => {
        :registrations => :account,
        :sessions => :sessions
      } do
    end
    resources :movies do
      collection do
        get :top
        get :series
        get :feed
        get :feed_all
        get :search
        get :weekly
      end
      member do
        get :douban_page
        get :douban_review
        get :fetch_douban
        get :fetch_cover
        get :fetch_bg
        get :fetch_fenopy
        get :fetch_sources
        post :suggest
      end
      resources :attachs
      resources :sources
    end

    resources :attach_entries, :path => 'entries' do
      collection do
        get :search
      end
    end

    resources :users

    root :to => "home#index"
    match "/info1", :to => "home#info1"

    namespace :admin do
      root :to => 'home#index'
      resources :site_configs
      resources :movies do
        member do
          post :delete_attachs
        end
      end
      resources :users
      resources :attach_entries
      namespace :homeland, :path => "bbs" do
        resources :topics
        resources :nodes
        resources :replies
        resources :sections
      end
    end
    mount Homeland::Engine, :at => "/bbs"
  end

  namespace :api do
    resources :movies do
      collection do
        get :search
        post :multi
        get :multi
        get :top
      end
    end
  end
end

app/models/user.rb
# coding: utf-8
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::BaseModel

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  ## Database authenticatable
  field :email,              :type => String, :null => false, :default => ""
  field :encrypted_password, :type => String, :null => false, :default => ""

  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  field :name
  field :bio
  field :website
  field :verified, :type => Boolean, :default => false

  attr_accessor :captcha

  mount_uploader :avatar, AvatarUploader

  validates_uniqueness_of :name

  index :name
  index :email

  def to_s
    self.name
  end

  def avatar_small_url
    self.avatar.url(:normal)
  end

  # 是否是管理员
  def admin?
    Setting.admin_emails.include?(self.email)
  end

  # 是否可信
  def verified?
    self.admin? or self.verified == true
  end

  def update_with_password(params={})
    if !params[:current_password].blank? or !params[:password].blank? or !params[:password_confirmation].blank?
      super
    else
      params.delete(:current_password)
      self.update_without_password(params)
    end
  end

  def admin?
    self.email.in?(Setting.admin_emails)
  end

  def self.find_by_username(s)
    where(name: s).first
  end
end

app/controllers/admin/users_controller.rb
# coding: UTF-8
class Admin::UsersController < Admin::ApplicationController

  def index
    @users = User.recent.paginate(:page => params[:page], :per_page => 20)

    respond_to do |format|
      format.html # index.html.erb
      format.json
    end
  end

  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json
    end
  end

  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(admin_users_path, :notice => 'User 创建成功。') }
        format.json
      else
        format.html { render :action => "new" }
        format.json
      end
    end
  end

  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(admin_users_path, :notice => 'User 更新成功。') }
        format.json
      else
        format.html { render :action => "edit" }
        format.json
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(admin_users_path,:notice => "删除成功。") }
      format.json
    end
  end
end

app/controllers/users_controller.rb
# coding: utf-8
class UsersController < ApplicationController
  before_filter :find_user, :only => [:show,:uploaded]
  def index
    @recent_users = User.recent.limit(30)
    drop_breadcrumb("会员")
  end

  def show
  end

  private
  def find_user
    @user = User.find(params[:id])
    drop_breadcrumb("会员", users_path)
    drop_breadcrumb(@user.name, user_path(@user))
  end
end

app/helpers/users_helper.rb
# coding: utf-8
require "digest/md5"
module UsersHelper
  # 生成用户 login 的链接，user 参数可接受 user 对象或者 字符串的 login
  def user_name_tag(user,options = {})
    return "" if user.blank?
    link_to(user.name, user_path(user.id), :class => "uname")
  end

  def user_name_str_tag(name, id)
    return "" if name.blank? or id.blank?
    link_to(name, user_path(id), :class => "uname")
  end

  def user_avatar_width_for_size(style)
    case style
      when :normal then 48
      when :small then 16
      when :large then 64
      when :big then 120
      else ""
    end
  end

  def user_avatar_tag(user,  opts = {})
    link = opts[:link] || true
    style = opts[:style] || :small

    width = user_avatar_width_for_size(style)

    if user.blank?
      hash = Digest::MD5.hexdigest("")
      return image_tag( User.new.avatar.url(style), :style => "width:#{width}px;height:#{width}px;")
    end

    img = image_tag(user.avatar.url(style), :style => "width:#{width}px;height:#{width}px;")

    if link
      raw %(<a href="#{user_path(user.id)}"class="uavatar">#{img}</a>)
    else
      raw img
    end
  end

  def verified_user?
    return false if current_user.blank?
    current_user.verified?
  end

  def notify_new_icon_tag(notify)
    return "" if current_user.blank?
    if notify.cache_key.split("_").last.to_i > (current_user.last_read_mention_at.to_i || 0)
      raw content_tag("span", "New", :class => "badge badge-important")
    end
  end
end

app/views/admin/users/_base.html.erb
<%= content_for :styles do %>
<% end %>

<ul class="nav nav-tabs">
  <li<%= " class=active" if action_name == "index" %>>
    <%= link_to "列表", admin_users_path %>
  </li>
  <% if action_name.in?(%w(edit update)) %>
  <li class="active"><%= link_to "修改", edit_admin_user_path(@user) %></li>
  <% end %>
  <li<%= " class=active" if action_name.in?(%w(new create)) %>><%= link_to "新建", new_admin_user_path %></li>
</ul>

app/views/admin/users/_form.html.erb
<div id="admin_user" class="form">

<%= simple_form_for([:admin,@user]) do |f| %>
  <%= render "/shared/error_messages", :target => @user  %>
  <fieldset>
      <%= f.input :email %>
      <%= f.input :name %>
      <%= f.input :bio %>
      <%= f.input :website %>
      <%= f.input :verified, :as => :boolean %>
      <%= f.input :points, :as => :integer %>
      <%= f.input :level, :as => :integer %>
      <div class="form-actions">
      <%= f.submit "保存", :class => "btn btn-primary" %> or <%= link_to "取消", admin_users_path %>
    </div>
  </fieldset>
<% end %>
</div>

app/views/admin/users/edit.html.erb
<%= render 'base' %>
<%= render 'form' %>

app/views/admin/users/index.html.erb
<%= render 'base' %>
<div id="admin_users">
  <table class="table table-striped table-bordered table-condensed">
    <thead>
      <tr>
        <th>编号</th>
        <th><%= t("mongoid.attributes.user.email") %></th>
        <th><%= t("mongoid.attributes.user.name") %></th>
        <th><%= t("mongoid.attributes.user.verified") %></th>
        <th>创建时间</th>
        <th class="opts"></th>
      </tr>
    </thead>
    <tbody>
    <% @users.each do |item| %>
    <tr class="<%= cycle("","even") %>">
        <td><%= item.id %></td>
        <td><%= item.email %></td>
        <td><%= item.name %></td>
        <td><%= item.verified %></td>
        <td><%= l(item.created_at, :format => :long) %></td>
        <td>
          <%= link_to "", edit_admin_user_path(item.id), :class => "icon-edit" %>
          <%= link_to '', admin_user_path(item.id), :method => :delete, :'data-confirm' => '确定要删除吗?', :class => "icon-remove" %>
        </td>
      </tr>
    <% end %>
    <tbody>
  </table>
  <%= will_paginate @users %>
</div>

app/views/admin/users/new.html.erb
<%= render 'base' %>
<%= render 'form' %>

app/views/admin/users/show.html.erb
<%= render 'base' %>
<div id="admin_user">
  <%= link_to '修改', edit_admin_user_path(@user), :class => "btn small success" %>
    <p>
    <b>Email:</b>
    <%= @user.email %>
  </p>
    <p>
    <b>Name:</b>
    <%= @user.name %>
  </p>
    <p>
    <b>Bio:</b>
    <%= @user.bio %>
  </p>
    <p>
    <b>Website:</b>
    <%= @user.website %>
  </p>
  </div>